# default profile
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    database: mysql

  # swagger issue
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jwt:
    secret: secret

server:
  port: 8080
  tomcat:
    connection-timeout: 30000
    max-threads: 100
    min-spare-threads: 50
    accept-count: 50
    uri-encoding: UTF-8
  forward-headers-strategy: framework

# swagger
springdoc:
  version: '1.0'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/v1/**
